// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DefaultConfig():Promise<main.Config>;

export function DeleteConfig(arg1:string):Promise<Array<main.NamedConfig>>;

export function ExportConfig(arg1:main.Config):Promise<string>;

export function GetSnapshot():Promise<main.Snapshot>;

export function ImportConfig():Promise<main.Config>;

export function ListConfigs():Promise<Array<main.NamedConfig>>;

export function RecentRequests(arg1:number):Promise<Array<main.RequestRecord>>;

export function SaveConfig(arg1:string,arg2:main.Config):Promise<Array<main.NamedConfig>>;

export function StartBench(arg1:main.Config):Promise<main.Snapshot>;

export function StopBench():Promise<main.Snapshot>;
