// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultConfig() {
  return window['go']['main']['App']['DefaultConfig']();
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function RecentRequests(arg1) {
  return window['go']['main']['App']['RecentRequests'](arg1);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function StartBench(arg1) {
  return window['go']['main']['App']['StartBench'](arg1);
}

export function StopBench() {
  return window['go']['main']['App']['StopBench']();
}
